export const CountriesData = [
  { label: 'United States (+1)', value: '1' },
  { label: 'Bahamas (+242)', value: '2' },
  { label: 'Barbados (+246)', value: '3' },
  { label: 'Anguilla (+264)', value: '4' },
  { label: 'Antigua (+268)', value: '5' },
  { label: 'British Virgin Islands (+284)', value: '6' },
  { label: 'Cayman Islands (+345)', value: '7' },
  { label: 'Bermuda (+441)', value: '8' },
  { label: 'Turks and Caicos Islands (+473)', value: '9' },
  { label: 'Jamaica (+876)', value: '10' },
  { label: 'Montserrat (+664)', value: '11' },
  { label: 'Sint Maarten (+721)', value: '12' },
  { label: 'Saint Lucia (+758)', value: '13' },
  { label: 'Dominica (+767)', value: '14' },
  { label: 'Saint Vincent and the Grenadines (+784)', value: '15' },
  { label: 'Dominican Republic (+829)', value: '16' },
  { label: 'Trinidad and Tobagoc (+868)', value: '17' },
  { label: 'Saint Kitts and Nevis (+869)', value: '18' },
  { label: 'Egypt (+20)', value: '19' },
  { label: 'Nigeria (+234)', value: '20' },
  { label: 'South Sudan (+211)', value: '21' },
  { label: 'Morocco (+212)', value: '22' },
  { label: 'Algeria (+213)', value: '23' },
  { label: 'Tunisia (+216)', value: '24' },
  { label: 'Libya (+218)', value: '25' },
  { label: 'Gambia (+220)', value: '26' },
  { label: 'Senegal (+221)', value: '27' },
  { label: 'Mauritania (+222)', value: '28' },
  { label: 'Mali (+223)', value: '29' },
  { label: 'Guinea (+224)', value: '30' },
  { label: 'Ivory Coast (+225)', value: '31' },
  { label: 'Burkina Faso (+226)', value: '32' },
  { label: 'Niger (+227)', value: '33' },
  { label: 'Togo (+228)', value: '34' },
];
