import { FcAbout, FcHome } from 'react-icons/fc';
import { AiFillHome } from 'react-icons/ai';
import { GrHomeRounded } from 'react-icons/gr';
import {
  GiCaveEntrance,
  GiFishingBoat,
  GiWaterPolo,
} from 'react-icons/gi';
import { FaUmbrellaBeach, FaTreeCity } from 'react-icons/fa6';
import { FaFacebookF } from 'react-icons/fa';
import { HiMiniHomeModern } from 'react-icons/hi2';

export const Data = [
  {
    id: 1,
    title: 'Villarrubia, Spain',
    distance: '4,564 kilometers away',
    date: 'Aug 20 - 25',
    price: 120,
    category: 'Design',
    rating: 4.92,
    icon: <FcHome />,
    image: require('./images/Fourty-one.webp'),
    tax: 563,
  },
  {
    id: 2,
    title: 'Calpe, Spain',
    distance: '6,974 kilometers away',
    date: 'Aug 29 - Sep 3',
    price: 300,
    category: 'Design',
    rating: '5.0',
    icon: <FcHome />,
    image: require('./images/Second-picture, second-image.webp'),
    tax: 2000,
  },
  {
    id: 3,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake',
    rating: 4.86,
    icon: <FaFacebookF />,
    image: require('./images/Fourteen.webp'),
    tax: 1163,
  },
  {
    id: 4,
    title: 'Marbella, Spain ',
    distance: '3,445 kilometers away',
    date: 'Aug 11 - 18',
    price: 725,
    category: 'Design',
    rating: 4.2,
    icon: <FcHome />,
    image: require('./images/Third picture.webp'),
    tax: 5000,
  },
  {
    id: 5,
    title: 'Tarifa, Spain ',
    distance: 'Featured in Elle Decor',
    date: 'Sep 9 - 15',
    price: 309,
    category: 'Design',
    rating: 4.95,
    icon: <FcHome />,
    image: require('./images/Fourth Picture.webp'),
    tax: 600,
  },
  {
    id: 6,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake',
    rating: 4.86,
    icon: <FaFacebookF />,
    image: require('./images/Fifteen.webp'),
    tax: 7000,
  },
  {
    id: 7,
    title: 'Marrakesh, Morrocco',
    distance: 'Featured in Maison du Maroc',
    date: 'Jul 29 - Aug 3',
    price: 700,
    category: 'Design',
    rating: 4.94,
    icon: <FcHome />,
    image: require('./images/Fifth Picture.webp'),
    tax: 1000,
  },
  {
    id: 8,
    title: 'Porches, Portugal',
    distance: 'Designed by Marc Gispert',
    date: 'Jul 25 -Aug 1',
    price: 500,
    category: 'Design',
    rating: 4.7,
    icon: <FcHome />,
    image: require('./images/Sixth Picture.webp'),
    tax: 800,
  },
  {
    id: 9,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake',
    rating: 4.86,
    icon: <FaFacebookF />,
    image: require('./images/Sixteen.webp'),
    tax: 900,
  },
  {
    id: 10,
    title: 'Illes Balears, Spain',
    distance: '3,617 kilometers away',
    date: 'Jul 30 - Aug 15',
    price: 400,
    category: 'Design',
    rating: 4.91,
    icon: <FcHome />,
    image: require('./images/Eight Picture.webp'),
    tax: 790,
  },
  {
    id: 11,
    title: 'Guia, Portugal ',
    distance: '3,607 kilometers away',
    date: 'Jul 15 - 22',
    price: 250,
    category: 'Design',
    rating: 4.3,
    icon: <FcHome />,
    image: require('./images/Ninth Picture.webp'),
    tax: 430,
  },
  {
    id: 12,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake',
    rating: 4.86,
    icon: <FaFacebookF />,
    image: require('./images/Seventeen.webp'),
    tax: 2200,
  },
  {
    id: 13,
    title: 'Malaga, Spain  ',
    distance: '3,476 kilometers away',
    date: 'Sep 9 - 15',
    price: 430,
    category: 'Design',
    rating: 4.91,
    icon: <FcHome />,
    image: require('./images/Thirteen.webp'),
    tax: 1500,
  },
  {
    id: 14,
    title: 'Porches, Portugal',
    distance: '3,476 kilometers away',
    date: 'Sep 9 - 15',
    price: 430,
    category: 'Design',
    rating: 4.91,
    icon: <FcHome />,
    image: require('./images/Twelve.webp'),
    tax: 1200,
  },
  {
    id: 15,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake',
    rating: 4.86,
    icon: <FaFacebookF />,
    image: require('./images/Eighteen.webp'),
    tax: 590,
  },
  {
    id: 16,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake',
    rating: 4.86,
    icon: <FaFacebookF />,
    image: require('./images/Nineteen.webp'),
    tax: 4300,
  },
  {
    id: 17,
    title: 'Chania, Greece',
    distance: '4 min walk to Mirror of Venus Lake',
    date: 'Oct 1 - 26',
    price: 317,
    category: 'Lake',
    icon: <FaFacebookF />,
    rating: 4.06,
    image: require('./images/Twenty-eight.webp'),
    tax: 900,
  },
  {
    id: 18,
    title: 'Chania, Greece',
    distance: '13 min walk to Mirror of Venus Lake',
    date: 'Feb 1 - 26',
    price: 307,
    category: 'Lake',
    rating: 4.96,
    icon: <FaFacebookF />,
    image: require('./images/Thirty.webp'),
    tax: 10000,
  },
  {
    id: 19,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Bed & Breakfast',
    rating: 3.86,
    icon: <FcAbout />,
    image: require('./images/Twenty.webp'),
    tax: 780,
  },
  {
    id: 20,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'July 1 - 26',
    price: 357,
    category: 'Bed & Breakfast',
    rating: 4.86,
    icon: <FcAbout />,
    image: require('./images/Twenty-one.webp'),
    tax: 1400,
  },
  {
    id: 21,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'May 1 - 26',
    price: 357,
    category: 'Bed & Breakfast',
    rating: 4.16,
    icon: <FcAbout />,
    image: require('./images/Twenty-two.webp'),
    tax: 2200,
  },
  {
    id: 22,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'June 1 - 26',
    price: 357,
    category: 'Bed & Breakfast',
    rating: 4.86,
    icon: <FcAbout />,
    image: require('./images/Twenty-three.webp'),
    tax: 3000,
  },
  {
    id: 23,
    title: 'Tarifa, Spain ',
    distance: 'Featured in Elle Decor',
    date: 'Jan 1 - 15',
    price: 309,
    category: 'Bed & Breakfast',
    rating: 4.35,
    icon: <FcAbout />,
    image: require('./images/Twenty-four.webp'),
    tax: 2000,
  },
  {
    id: 24,
    title: 'Bagladesh, Spain ',
    distance: 'Featured in Elle Decor',
    date: 'Dec 6 - 15',
    price: 309,
    category: 'Bed & Breakfast',
    rating: 4.95,
    icon: <FcAbout />,
    image: require('./images/Twenty-five.webp'),
    tax: 500,
  },
  {
    id: 25,
    title: 'Marrakesh, Morrocco',
    distance: 'Featured in Maison du Maroc',
    date: 'Aug 29 - Aug 3',
    price: 700,
    category: 'Bed & Breakfast',
    rating: 4.94,
    icon: <FcAbout />,
    image: require('./images/Twenty-six.webp'),
    tax: 20000,
  },
  {
    id: 26,
    title: 'Pluto, Morrocco',
    distance: 'Featured in Maison du Maroc',
    date: 'Jul 22 - Aug 3',
    price: 700,
    category: 'Bed & Breakfast',
    rating: 4.9,
    icon: <FcAbout />,
    image: require('./images/Twenty-seven.webp'),
    tax: 5000,
  },
  {
    id: 27,
    title: 'Guia, Portugal ',
    distance: '3,007 kilometers away',
    date: 'Jul 15 - 22',
    price: 200,
    category: 'Design',
    rating: 4.1,
    icon: <FcHome />,
    image: require('./images/Thirty-one.webp'),
    tax: 3000,
  },
  {
    id: 28,
    title: 'Ronda, Spain',
    distance: '1,607 kilometers away',
    date: 'Jun 15 - 22',
    price: 550,
    category: 'Design',
    rating: 4.8,
    icon: <FcHome />,
    image: require('./images/Thirty-two.webp'),
    tax: 5200,
  },
  {
    id: 29,
    title: 'Dubai, UAE',
    distance: '5,607 kilometers away',
    date: 'Jul 10 - 22',
    price: 930,
    category: 'Iconic cities',
    rating: 4.8,
    icon: <AiFillHome />,
    image: require('./images/Fourty-one.webp'),
    tax: 260,
  },
  {
    id: 30,
    title: 'Raol, Spain',
    distance: '2,607 kilometers away',
    date: 'Aug 9 - 22',
    price: 50,
    category: 'Iconic cities',
    rating: 4.3,
    icon: <AiFillHome />,
    image: require('./images/Thirty-four.webp'),
    tax: 400,
  },
  {
    id: 31,
    title: 'San Fransisco, USA',
    distance: '6,377 kilometers away',
    date: 'Nov 9 - 22',
    price: 500,
    category: 'Iconic cities',
    rating: 4.3,
    icon: <AiFillHome />,
    image: require('./images/Thirty-five.webp'),
    tax: 600,
  },
  {
    id: 32,
    title: 'Raol, Spain',
    distance: '2,500 kilometers away',
    date: 'Mar 9 - 22',
    price: 500,
    category: 'Iconic cities',
    rating: 4.4,
    icon: <AiFillHome />,
    image: require('./images/Thirty-six.webp'),
    tax: 1000,
  },
  {
    id: 33,
    title: 'Florence, Italy',
    distance: '4,777 kilometers away',
    date: 'Apr 9 - 29',
    price: 230,
    category: 'Iconic cities',
    rating: 4.7,
    icon: <AiFillHome />,
    image: require('./images/Thirty-seven.webp'),
    tax: 800,
  },
  {
    id: 34,
    title: 'New York, New York',
    distance: '607 kilometers away',
    date: 'Aug 2 - 22',
    price: 500,
    category: 'Iconic cities',
    rating: 4.1,
    icon: <AiFillHome />,
    image: require('./images/Thirty-eight.webp'),
    tax: 750,
  },
  {
    id: 35,
    title: 'Sao Paulo, Brazil',
    distance: '2,607 kilometers away',
    date: 'Aug 16 - 20',
    price: 50,
    category: 'Iconic cities',
    rating: 4.3,
    icon: <AiFillHome />,
    image: require('./images/Thirty-nine.webp'),
    tax: 200,
  },
  {
    id: 36,
    title: 'London, Uk',
    distance: '5,021 kilometers away',
    date: 'Aug 5 - 11',
    price: 3245,
    category: 'Iconic cities',
    rating: 4.7,
    icon: <AiFillHome />,
    image: require('./images/Fourty.webp'),
    tax: 5325,
  },
  {
    id: 37,
    title: 'Vis, Croatia',
    distance: '4.4 hectares',
    date: 'Aug 5 - 11',
    price: 1901,
    category: 'Island',
    rating: 4.3,
    icon: <GrHomeRounded />,
    image: require('./images/Fourty-two.webp'),
    tax: 5900,
  },
  {
    id: 38,
    title: 'Murter, Croatia',
    distance: '1 hectares',
    date: 'Sep 5 - 11',
    price: 371,
    category: 'Island',
    rating: 4.5,
    icon: <GrHomeRounded />,
    image: require('./images/Fourty-three.webp'),
    tax: 850,
  },
  {
    id: 39,
    title: 'Vis, Croatia',
    distance: '4.4 hectares',
    date: 'Jul 30 - Aug 4',
    price: 190,
    category: 'Island',
    icon: <GrHomeRounded />,
    rating: 4.3,
    image: require('./images/Fourty-six.webp'),
    tax: 250,
  },
  {
    id: 40,
    title: 'Vis, Croatia',
    distance: '4.4 hectares',
    date: 'Sep 23 - 30',
    price: 230,
    category: 'Island',
    icon: <GrHomeRounded />,
    rating: 4.97,
    image: require('./images/Fourty-five.webp'),
    tax: 860,
  },
  {
    id: 41,
    title: 'Otok Prsnjak, Croatia',
    distance: '5.5 hectares',
    date: 'Jul 22 - 29',
    price: 2815,
    category: 'Island',
    icon: <GrHomeRounded />,
    rating: 4.99,
    image: require('./images/Fourty-seven.webp'),
    tax: 5000,
  },
  {
    id: 42,
    title: 'Otok Prsnjak, Croatia',
    distance: '4,338 kilometers away',
    date: 'Aug 61 - 21',
    price: 115,
    category: 'Island',
    icon: <GrHomeRounded />,
    rating: 4.86,
    image: require('./images/Fourty-eight.webp'),
    tax: 400,
  },
  {
    id: 43,
    title: 'Illa de Tagomago, Spain',
    distance: '3,628 kilometers away',
    date: 'Jul 22 - 29',
    price: 22815,
    category: 'Island',
    icon: <GrHomeRounded />,
    rating: 3.7,
    image: require('./images/Fourty-nine.webp'),
    tax: 50000,
  },
  {
    id: 44,
    title: 'Jinja, Uganda',
    distance: '3.3 hectares ',
    date: 'Jul 21 - 29',
    price: 228,
    category: 'Island',
    icon: <GrHomeRounded />,
    rating: 3.4,
    image: require('./images/Fifty.webp'),
    tax: 700,
  },
  {
    id: 45,
    title: 'Athens, Greece',
    distance: '4,055 kilometers away',
    date: 'Sep 15 - 21',
    price: 222,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 4.88,
    image: require('./images/First-Boat.webp'),
    tax: 840,
  },
  {
    id: 46,
    title: 'Eivissa, Spain',
    distance: '3,615 kilometers away ',
    date: 'Jul 21 - 29',
    price: 33228,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 3.4,
    image: require('./images/Second-Boat.webp'),
    tax: 50000,
  },
  {
    id: 47,
    title: 'Dakta, Turkey',
    distance: '4,172 kilometers away',
    date: 'Sep 15 - 21',
    price: 218,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 4.88,
    image: require('./images/Nine-Boat.webp'),
    tax: 600,
  },
  {
    id: 48,
    title: 'Dakta, Turkey',
    distance: '4,172 kilometers away',
    date: 'Sep 15 - 21',
    price: 282,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 4.18,
    image: require('./images/Fourth-Boat.webp'),
    tax: 700,
  },
  {
    id: 49,
    title: 'Mugla, Turkey',
    distance: '4,217 kilometers away',
    date: 'Jun 15 - Aug 3',
    price: 7000,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 3.83,
    image: require('./images/Fifth-Boat.webp'),
    tax: 10000,
  },
  {
    id: 50,
    title: 'Marmaris, Turkey',
    distance: '3,954 kilometers away',
    date: 'Sep 15 - 21',
    price: 2280,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 4.88,
    image: require('./images/Sixth-Boat.webp'),
    tax: 5200,
  },
  {
    id: 51,
    title: 'Capri, Turkey',
    distance: '1,172 kilometers away',
    date: 'Jan 15 - Feb 21',
    price: 900,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 4.78,
    image: require('./images/Seven-Boat.webp'),
    tax: 1500,
  },
  {
    id: 52,
    title: 'Dakta, Turkey',
    distance: '4,172 kilometers away',
    date: 'Dec 1 - 21',
    price: 3000,
    category: 'Boats',
    icon: <GiFishingBoat />,
    rating: 4.98,
    image: require('./images/Eight-Boat.webp'),
    tax: 6000,
  },
  {
    id: 53,
    title: ' Gulfi, RG - Sicily, Italy',
    distance: '3,589 kilometers away',
    date: 'Sep 1 - 31',
    price: 600,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: 4.94,
    image: require('./images/Country-one.webp'),
    tax: 9000,
  },
  {
    id: 54,
    title: ' Cutar, Spain',
    distance: '3,289 kilometers away',
    date: 'Sep 30 - Nov 5',
    price: 700,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: 4.98,
    image: require('./images/Fifty-one.jpg'),
    tax: 980,
  },
  {
    id: 55,
    title: ' Tolox, Spain',
    distance: '3,469 kilometers away',
    date: 'Aug 30 - Nov 5',
    price: 625,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: 4.5,
    image: require('./images/Fifty-two.webp'),
    tax: 2000,
  },
  {
    id: 56,
    title: ' La Palma, Spain',
    distance: '3,347 kilometers away',
    date: 'Sep 2 - 7',
    price: 820,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: 4.56,
    image: require('./images/Fifty-three.webp'),
    tax: 6200,
  },
  {
    id: 57,
    title: 'Koroni, Greece',
    distance: '3,847 kilometers away',
    date: 'Sep 2 - Dec 8',
    price: 3820,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: '5.0',
    image: require('./images/Country-two.webp'),
    tax: 3100,
  },
  {
    id: 58,
    title: 'Madonna delle, Italy',
    distance: '3,484 kilometers away',
    date: 'Jul 29 - Aug 5',
    price: 820,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: 4.86,
    image: require('./images/Country-three.webp'),
    tax: 2000,
  },
  {
    id: 59,
    title: ' Vila do Bispo, Portugal',
    distance: '3,347 kilometers away',
    date: 'Nov 2 - 17',
    price: 1820,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: 4.26,
    image: require('./images/Country-four.webp'),
    tax: 2750,
  },
  {
    id: 60,
    title: 'Episkopi, Greece',
    distance: '3,847 kilometers away',
    date: 'Oct 15 - 21',
    price: 2820,
    category: 'Countryside',
    icon: <FaTreeCity />,
    rating: 4.5,
    image: require('./images/Counrt-five.webp'),
    tax: 4000,
  },
  {
    id: 61,
    title: 'Malaga, Spain',
    distance: '3,847 kilometers away',
    date: 'Sep 15 - 21',
    price: 800,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: 4.4,
    image: require('./images/Beachfront-one.webp'),
    tax: 2500,
  },
  {
    id: 62,
    title: 'Torre del Mar, Spain',
    distance: '3,457 kilometers away',
    date: 'Oct 15 - 21',
    price: 104,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: 4.8,
    image: require('./images/Beachfront-two.webp'),
    tax: 350,
  },
  {
    id: 63,
    title: 'Candaleria, Spain',
    distance: '3,447 kilometers away',
    date: 'Sep 15 - 21',
    price: 800,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: 4.2,
    image: require('./images/Beachfront-three.webp'),
    tax: 5000,
  },
  {
    id: 64,
    title: 'Noto, Italy',
    distance: '3,247 kilometers away',
    date: 'Jun 15 - 21',
    price: 200,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: 4.1,
    image: require('./images/Beachfront-four.webp'),
    tax: 550,
  },
  {
    id: 65,
    title: 'El Rosario, Spain',
    distance: '3,547 kilometers away',
    date: 'Mar 15 - 21',
    price: 400,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: 4.5,
    image: require('./images/Beachfront-five.webp'),
    tax: 570,
  },
  {
    id: 66,
    title: 'Benalmadena, Spain',
    distance: 'Playa da las Arenas',
    date: 'Sep 15 - 21',
    price: 388,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: '5.0',
    image: require('./images/Beachfront-six.webp'),
    tax: 563,
  },
  {
    id: 67,
    title: 'Bubaque, Guinea',
    distance: '2,190 kilometers away',
    date: 'Jul 28 - Aug 2',
    price: 191,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: 3.75,
    image: require('./images/Beachfront-seven.webp'),
    tax: 3550,
  },
  {
    id: 68,
    title: 'Faro, Portugal',
    distance: '3,596 kilometers away',
    date: 'Jul 22 - 29',
    price: 1850,
    category: 'Beachfront',
    icon: <FaUmbrellaBeach />,
    rating: 4.2,
    image: require('./images/Beachfront-eight.webp'),
    tax: 2500,
  },
  {
    id: 69,
    title: 'Los Balcones, Spain',
    distance: '3,506 kilometers away',
    date: 'Jul 30 - Aug 29',
    price: 850,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: 4.33,
    image: require('./images/Cave-one.webp'),
    tax: 5200,
  },
  {
    id: 70,
    title: 'Guadix, Spain',
    distance: '3,493 kilometers away',
    date: 'Aug 30 - Dec 29',
    price: 812,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: 4.21,
    image: require('./images/Cave-two.webp'),
    tax: 1500,
  },
  {
    id: 71,
    title: 'Mozaga, Spain',
    distance: '3,080 kilometers away',
    date: 'Sep 30 - Dec 29',
    price: 112,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: 4.41,
    image: require('./images/Cave-three.webp'),
    tax: 540,
  },
  {
    id: 72,
    title: 'Purullena, Spain',
    distance: '3,499 kilometers away',
    date: 'Aug 26 -  29',
    price: 234,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: 4.5,
    image: require('./images/Cave-four.webp'),
    tax: 400,
  },
  {
    id: 73,
    title: 'Salobrena, Spain',
    distance: '3,443 kilometers away',
    date: 'Nov 28 - Dec 5',
    price: 476,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: '4.91',
    image: require('./images/Cave-nine.webp'),
    tax: 2300,
  },
  {
    id: 74,
    title: 'Setenil de las, Spain',
    distance: '3,492 kilometers away',
    date: 'Oct 19 - 29',
    price: 813,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: 4.21,
    image: require('./images/Cave-six.webp'),
    tax: 470,
  },
  {
    id: 75,
    title: 'Setenil de las, Spain',
    distance: '3,492 kilometers away',
    date: 'Aug 30 - Dec 29',
    price: 431,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: 4.21,
    image: require('./images/Cave-seven.webp'),
    tax: 560,
  },
  {
    id: 76,
    title: 'Setenil de las, Spain',
    distance: '3,492 kilometers away',
    date: 'Jul 30 - Dec 29',
    price: 451,
    category: 'Cave',
    icon: <GiCaveEntrance />,
    rating: 4.81,
    image: require('./images/Cave-eight.webp'),
    tax: 2000,
  },

  {
    id: 77,
    title: 'Los Balcones, Spain',
    distance: '3,506 kilometers away',
    date: 'Jul 30 - Aug 29',
    price: 850,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: 4.33,
    image: require('./images/Cave-one.webp'),
    tax: 5200,
  },
  {
    id: 78,
    title: 'Guadix, Spain',
    distance: '3,493 kilometers away',
    date: 'Aug 30 - Dec 29',
    price: 812,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: 4.21,
    image: require('./images/Cave-two.webp'),
    tax: 1500,
  },
  {
    id: 79,
    title: 'Mozaga, Spain',
    distance: '3,080 kilometers away',
    date: 'Sep 30 - Dec 29',
    price: 112,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: 4.41,
    image: require('./images/Cave-three.webp'),
    tax: 540,
  },
  {
    id: 80,
    title: 'Purullena, Spain',
    distance: '3,499 kilometers away',
    date: 'Aug 26 -  29',
    price: 234,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: 4.5,
    image: require('./images/Cave-four.webp'),
    tax: 400,
  },
  {
    id: 81,
    title: 'Salobrena, Spain',
    distance: '3,443 kilometers away',
    date: 'Nov 28 - Dec 5',
    price: 476,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: '4.91',
    image: require('./images/Cave-nine.webp'),
    tax: 2300,
  },
  {
    id: 82,
    title: 'Setenil de las, Spain',
    distance: '3,492 kilometers away',
    date: 'Oct 19 - 29',
    price: 811,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: 4.21,
    image: require('./images/Cave-six.webp'),
    tax: 470,
  },
  {
    id: 83,
    title: 'Setenil de las, Spain',
    distance: '3,492 kilometers away',
    date: 'Aug 30 - Dec 29',
    price: 41,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: 4.21,
    image: require('./images/Cave-seven.webp'),
    tax: 560,
  },
  {
    id: 84,
    title: 'Setenil de las, Spain',
    distance: '3,492 kilometers away',
    date: 'Jul 30 - Dec 29',
    price: 451,
    category: 'MiniHomes',
    icon: <HiMiniHomeModern />,
    rating: 4.81,
    image: require('./images/Cave-eight.webp'),
    tax: 2000,
  },
  {
    id: 85,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake&Design',
    rating: 4.86,
    icon: <GiWaterPolo />,
    image: require('./images/Seventeen.webp'),
    tax: 2200,
  },
  {
    id: 86,
    title: 'Malaga, Spain  ',
    distance: '3,476 kilometers away',
    date: 'Sep 9 - 15',
    price: 430,
    category: 'Lake&Design',
    rating: 4.91,
    icon: <GiWaterPolo />,
    image: require('./images/Thirteen.webp'),
    tax: 1500,
  },
  {
    id: 87,
    title: 'Porches, Portugal',
    distance: '3,476 kilometers away',
    date: 'Sep 9 - 15',
    price: 430,
    category: 'Lake&Design',
    rating: 4.91,
    icon: <GiWaterPolo />,
    image: require('./images/Twelve.webp'),
    tax: 1200,
  },
  {
    id: 88,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake&Design',
    rating: 4.86,
    icon: <GiWaterPolo />,
    image: require('./images/Eighteen.webp'),
    tax: 590,
  },
  {
    id: 89,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake&Design',
    rating: 4.86,
    icon: <GiWaterPolo />,
    image: require('./images/Nineteen.webp'),
    tax: 4300,
  },
  {
    id: 90,
    title: 'Chania, Greece',
    distance: '4 min walk to Mirror of Venus Lake',
    date: 'Oct 1 - 26',
    price: 317,
    category: 'Lake&Design',
    icon: <GiWaterPolo />,
    rating: 4.06,
    image: require('./images/Twenty-eight.webp'),
    tax: 900,
  },
  {
    id: 91,
    title: 'Chania, Greece',
    distance: '13 min walk to Mirror of Venus Lake',
    date: 'Feb 1 - 26',
    price: 307,
    category: 'Lake&Design',
    rating: 4.96,
    icon: <GiWaterPolo />,
    image: require('./images/Thirty.webp'),
    tax: 10000,
  },
  {
    id: 92,
    title: 'Chania, Greece',
    distance: '10 min walk to Mirror of Venus Lake',
    date: 'Sep 1 - 26',
    price: 357,
    category: 'Lake&Design',
    rating: 3.86,
    icon: <GiWaterPolo />,
    image: require('./images/Twenty.webp'),
    tax: 780,
  },
];
